# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=10, null=True)),
                ('apellido', models.CharField(blank=True, max_length=10, null=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('estatus', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
